In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/bestsellers with categories.csv")
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [ ]:
df.shape

(550, 7)

In [ ]:
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [ ]:
df.dtypes

Name            object
Author          object
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre           object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [ ]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [ ]:
df.isnull()

      Name  Author  User Rating  Reviews  Price   Year  Genre
0    False   False        False    False  False  False  False
1    False   False        False    False  False  False  False
2    False   False        False    False  False  False  False
3    False   False        False    False  False  False  False
4    False   False        False    False  False  False  False
..     ...     ...          ...      ...    ...    ...    ...
545  False   False        False    False  False  False  False
546  False   False        False    False  False  False  False
547  False   False        False    False  False  False  False
548  False   False        False    False  False  False  False
549  False   False        False    False  False  False  False

[550 rows x 7 columns]

In [ ]:
df.isnull().sum()
df['Author']

0                      JJ Smith
1                  Stephen King
2            Jordan B. Peterson
3                 George Orwell
4      National Geographic Kids
                 ...
545                 Jeff Kinney
546                 Jen Sincero
547                 Jen Sincero
548                 Jen Sincero
549                 Jen Sincero
Name: Author, Length: 550, dtype: object

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df
x=df.iloc[:,2:6].values# User Rating, Reviews, Price, Year
x

array([[4.7000e+00, 1.7350e+04, 8.0000e+00, 2.0160e+03],
       [4.6000e+00, 2.0520e+03, 2.2000e+01, 2.0110e+03],
       [4.7000e+00, 1.8979e+04, 1.5000e+01, 2.0180e+03],
       ...,
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0170e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0180e+03],
       [4.7000e+00, 1.4331e+04, 8.0000e+00, 2.0190e+03]])

In [ ]:
y=df.iloc[:,-1].values
y

array(['Non Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=45)

In [ ]:
X_test

array([[4.6000e+00, 1.9720e+04, 8.0000e+00, 2.0090e+03],
       [4.8000e+00, 2.9673e+04, 1.6000e+01, 2.0100e+03],
       [4.7000e+00, 1.0820e+04, 5.0000e+00, 2.0180e+03],
       [4.9000e+00, 1.9546e+04, 5.0000e+00, 2.0130e+03],
       [4.5000e+00, 7.2000e+02, 1.0000e+00, 2.0090e+03],
       [4.7000e+00, 4.3700e+03, 1.5000e+01, 2.0160e+03],
       [4.9000e+00, 8.8420e+03, 1.0000e+01, 2.0170e+03],
       [4.6000e+00, 6.9900e+03, 4.0000e+00, 2.0130e+03],
       [4.8000e+00, 1.8613e+04, 5.0000e+00, 2.0140e+03],
       [4.8000e+00, 3.9230e+03, 1.6000e+01, 2.0180e+03],
       [4.8000e+00, 2.6630e+03, 1.7000e+01, 2.0130e+03],
       [4.7000e+00, 2.3308e+04, 6.0000e+00, 2.0150e+03],
       [4.5000e+00, 4.3800e+02, 1.5000e+01, 2.0090e+03],
       [4.7000e+00, 2.2614e+04, 1.1000e+01, 2.0120e+03],
       [4.8000e+00, 1.0922e+04, 5.0000e+00, 2.0160e+03],
       [4.3000e+00, 1.9240e+03, 8.0000e+00, 2.0100e+03],
       [4.3000e+00, 1.3616e+04, 1.0000e+01, 2.0120e+03],
       [4.7000e+00, 2.5001e+04, 1.1000e+01, 2.0160e+03],
       [4.4000e+00, 3.5030e+03, 9.0000e+00, 2.0090e+03],
       [4.5000e+00, 3.4570e+03, 1.4000e+01, 2.0090e+03],
       [4.8000e+00, 4.6280e+03, 7.0000e+00, 2.0100e+03],
       [4.4000e+00, 1.2010e+03, 4.0000e+01, 2.0120e+03],
       [4.3000e+00, 1.4493e+04, 1.8000e+01, 2.0120e+03],
       [4.3000e+00, 1.8904e+04, 1.3000e+01, 2.0170e+03],
       [4.7000e+00, 5.4130e+03, 9.0000e+00, 2.0150e+03],
       [4.4000e+00, 7.4970e+03, 6.0000e+00, 2.0120e+03],
       [4.8000e+00, 2.1625e+04, 9.0000e+00, 2.0160e+03],
       [4.4000e+00, 7.0580e+03, 1.7000e+01, 2.0180e+03],
       [4.5000e+00, 1.9040e+03, 2.3000e+01, 2.0120e+03],
       [4.6000e+00, 9.7690e+03, 1.3000e+01, 2.0090e+03],
       [4.7000e+00, 2.5001e+04, 1.1000e+01, 2.0140e+03],
       [4.8000e+00, 1.2960e+03, 2.4000e+01, 2.0120e+03],
       [4.7000e+00, 9.2890e+03, 9.0000e+00, 2.0110e+03],
       [4.8000e+00, 5.8980e+03, 8.0000e+00, 2.0180e+03],
       [4.0000e+00, 5.0690e+03, 1.7000e+01, 2.0170e+03],
       [4.5000e+00, 1.3860e+03, 2.0000e+01, 2.0140e+03],
       [4.8000e+00, 1.0922e+04, 5.0000e+00, 2.0150e+03],
       [4.5000e+00, 2.7520e+03, 1.8000e+01, 2.0100e+03],
       [4.7000e+00, 1.5845e+04, 1.3000e+01, 2.0130e+03],
       [4.6000e+00, 2.1930e+04, 1.1000e+01, 2.0140e+03],
       [4.6000e+00, 3.1630e+03, 1.3000e+01, 2.0120e+03],
       [4.5000e+00, 8.5800e+03, 4.6000e+01, 2.0130e+03],
       [4.6000e+00, 1.0009e+04, 2.0000e+01, 2.0120e+03],
       [4.5000e+00, 1.3964e+04, 3.2000e+01, 2.0120e+03],
       [3.6000e+00, 1.4982e+04, 1.9000e+01, 2.0150e+03],
       [4.7000e+00, 3.6420e+03, 0.0000e+00, 2.0140e+03],
       [4.5000e+00, 3.6010e+03, 1.8000e+01, 2.0180e+03],
       [4.6000e+00, 1.3650e+03, 1.1000e+01, 2.0090e+03],
       [4.9000e+00, 3.1460e+03, 3.0000e+01, 2.0170e+03],
       [4.7000e+00, 9.2920e+03, 1.7000e+01, 2.0140e+03],
       [4.1000e+00, 7.9446e+04, 1.8000e+01, 2.0150e+03],
       [4.3000e+00, 1.3061e+04, 6.0000e+00, 2.0180e+03],
       [4.7000e+00, 1.9735e+04, 3.0000e+01, 2.0140e+03],
       [4.9000e+00, 1.9546e+04, 5.0000e+00, 2.0150e+03],
       [4.6000e+00, 1.0721e+04, 8.0000e+00, 2.0180e+03],
       [4.8000e+00, 2.6234e+04, 0.0000e+00, 2.0150e+03],
       [4.3000e+00, 7.1530e+03, 9.0000e+00, 2.0140e+03],
       [4.6000e+00, 2.1220e+03, 0.0000e+00, 2.0100e+03],
       [4.8000e+00, 9.5680e+03, 9.0000e+00, 2.0110e+03],
       [4.7000e+00, 3.2122e+04, 8.0000e+00, 2.0120e+03],
       [4.5000e+00, 1.8310e+03, 9.0000e+00, 2.0170e+03],
       [4.8000e+00, 8.9220e+03, 9.0000e+00, 2.0130e+03],
       [4.5000e+00, 6.6790e+03, 1.0500e+02, 2.0130e+03],
       [4.6000e+00, 1.0141e+04, 6.0000e+00, 2.0190e+03],
       [4.8000e+00, 2.3358e+04, 1.2000e+01, 2.0150e+03],
       [4.6000e+00, 1.0721e+04, 8.0000e+00, 2.0160e+03],
       [4.0000e+00, 5.7271e+04, 1.0000e+01, 2.0130e+03],
       [4.8000e+00, 6.9820e+03, 1.4000e+01, 2.0130e+03],
       [4.6000e+00, 9.3250e+03, 2.4000e+01, 2.0110e+03],
       [4.5000e+00, 2.2641e+04, 1.1000e+01, 2.0150e+03],
       [4.5000e+00, 3.6730e+03, 4.0000e+00, 2.0150e+03],
       [4.6000e+00, 4.6000e+02, 2.0000e+00, 2.0100e+03],
       [4.6000e+00, 1.0795e+04, 2.1000e+01, 2.0120e+03],
       [4.6000e+00, 2.6490e+04, 1.5000e+01, 2.0180e+03],
       [4.8000e+00, 9.7370e+03, 7.0000e+00, 2.0190e+03],
       [4.3000e+00, 8.0700e+02, 3.6000e+01, 2.0160e+03],
       [4.8000e+00, 8.0810e+03, 8.0000e+00, 2.0140e+03],
       [4.9000e+00, 9.3820e+03, 6.0000e+00, 2.0190e+03],
       [4.8000e+00, 7.6650e+03, 1.2000e+01, 2.0190e+03],
       [4.7000e+00, 1.5420e+03, 1.4000e+01, 2.0090e+03],
       [4.6000e+00, 2.2536e+04, 1.2000e+01, 2.0170e+03],
       [4.6000e+00, 2.3148e+04, 6.0000e+00, 2.0130e+03],
       [4.6000e+00, 2.6490e+04, 1.5000e+01, 2.0190e+03],
       [4.6000e+00, 7.5080e+03, 1.6000e+01, 2.0160e+03],
       [4.7000e+00, 4.7250e+03, 1.6000e+01, 2.0160e+03],
       [4.4000e+00, 4.2470e+03, 1.3000e+01, 2.0120e+03],
       [4.6000e+00, 1.1128e+04, 2.3000e+01, 2.0150e+03],
       [4.6000e+00, 7.5080e+03, 1.6000e+01, 2.0150e+03],
       [4.5000e+00, 1.3609e+04, 1.4000e+01, 2.0190e+03],
       [4.9000e+00, 1.9576e+04, 8.0000e+00, 2.0140e+03],
       [4.7000e+00, 5.4870e+03, 9.0000e+00, 2.0170e+03],
       [4.5000e+00, 4.7100e+02, 8.0000e+00, 2.0100e+03],
       [4.8000e+00, 1.6643e+04, 4.0000e+00, 2.0190e+03],
       [4.8000e+00, 5.4760e+03, 7.0000e+00, 2.0190e+03],
       [4.6000e+00, 2.7098e+04, 1.5000e+01, 2.0140e+03],
       [4.8000e+00, 2.5554e+04, 8.0000e+00, 2.0150e+03],
       [4.6000e+00, 2.7440e+03, 1.2000e+01, 2.0190e+03],
       [4.5000e+00, 2.5860e+03, 5.0000e+00, 2.0140e+03],
       [4.5000e+00, 2.4260e+03, 8.0000e+00, 2.0150e+03],
       [4.5000e+00, 3.4570e+03, 1.4000e+01, 2.0120e+03],
       [4.2000e+00, 1.6490e+03, 1.3000e+01, 2.0110e+03],
       [4.6000e+00, 1.1128e+04, 2.3000e+01, 2.0160e+03],
       [4.6000e+00, 1.0426e+04, 2.0000e+01, 2.0090e+03],
       [4.6000e+00, 6.9900e+03, 4.0000e+00, 2.0170e+03],
       [4.5000e+00, 2.6741e+04, 8.0000e+00, 2.0110e+03],
       [4.6000e+00, 1.0927e+04, 6.0000e+00, 2.0140e+03],
       [4.2000e+00, 1.3020e+03, 1.1000e+01, 2.0100e+03],
       [4.7000e+00, 6.3770e+03, 7.0000e+00, 2.0120e+03],
       [4.8000e+00, 2.0910e+03, 1.2000e+01, 2.0120e+03],
       [4.3000e+00, 5.2720e+03, 1.6000e+01, 2.0190e+03]])

In [ ]:
X_train

array([[4.8000e+00, 2.3047e+04, 6.0000e+00, 2.0180e+03],
       [4.8000e+00, 1.4038e+04, 4.0000e+00, 2.0170e+03],
       [4.8000e+00, 8.8370e+03, 5.0000e+00, 2.0190e+03],
       ...,
       [4.4000e+00, 1.5526e+04, 1.4000e+01, 2.0160e+03],
       [4.8000e+00, 2.1625e+04, 9.0000e+00, 2.0170e+03],
       [4.7000e+00, 9.2890e+03, 9.0000e+00, 2.0120e+03]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
X_test

array([[-1.08861812e-01,  6.48020559e-01, -4.77447139e-01,
        -1.55580274e+00],
       [ 7.62032687e-01,  1.49054600e+00,  2.78904764e-01,
        -1.24407542e+00],
       [ 3.26585437e-01, -1.05368009e-01, -7.61079102e-01,
         1.24974319e+00],
       [ 1.19747994e+00,  6.33291389e-01, -7.61079102e-01,
        -3.08893440e-01],
       [-5.44309062e-01, -9.60337058e-01, -1.13925505e+00,
        -1.55580274e+00],
       [ 3.26585437e-01, -6.51363095e-01,  1.84360776e-01,
         6.26288535e-01],
       [ 1.19747994e+00, -2.72806502e-01, -2.88359163e-01,
         9.38015860e-01],
       [-1.08861812e-01, -4.29579045e-01, -8.55623090e-01,
        -3.08893440e-01],
       [ 7.62032687e-01,  5.54312565e-01, -7.61079102e-01,
         2.83388477e-03],
       [ 7.62032687e-01, -6.89201824e-01,  2.78904764e-01,
         1.24974319e+00],
       [ 7.62032687e-01, -7.95861329e-01,  3.73448752e-01,
        -3.08893440e-01],
       [ 3.26585437e-01,  9.51746197e-01, -6.66535115e-01,
         3.14561210e-01],
       [-5.44309062e-01, -9.84208471e-01,  1.84360776e-01,
        -1.55580274e+00],
       [ 3.26585437e-01,  8.92998819e-01, -1.93815175e-01,
        -6.20620766e-01],
       [ 7.62032687e-01, -9.67336685e-02, -7.61079102e-01,
         6.26288535e-01],
       [-1.41520356e+00, -8.58417976e-01, -4.77447139e-01,
        -1.24407542e+00],
       [-1.41520356e+00,  1.31314512e-01, -2.88359163e-01,
        -6.20620766e-01],
       [ 3.26585437e-01,  1.09505933e+00, -1.93815175e-01,
         6.26288535e-01],
       [-9.79756312e-01, -7.24754993e-01, -3.82903151e-01,
        -1.55580274e+00],
       [-5.44309062e-01, -7.28648911e-01,  8.98167885e-02,
        -1.55580274e+00],
       [ 7.62032687e-01, -6.29523292e-01, -5.71991127e-01,
        -1.24407542e+00],
       [-9.79756312e-01, -9.19620215e-01,  2.54796047e+00,
        -6.20620766e-01],
       [-1.41520356e+00,  2.05552913e-01,  4.67992740e-01,
        -6.20620766e-01],
       [-1.41520356e+00,  5.78945831e-01, -4.72719939e-03,
         9.38015860e-01],
       [ 3.26585437e-01, -5.63072727e-01, -3.82903151e-01,
         3.14561210e-01],
       [-9.79756312e-01, -3.86661291e-01, -6.66535115e-01,
        -6.20620766e-01],
       [ 7.62032687e-01,  8.09279572e-01, -3.82903151e-01,
         6.26288535e-01],
       [-9.79756312e-01, -4.23822817e-01,  3.73448752e-01,
         1.24974319e+00],
       [-5.44309062e-01, -8.60110984e-01,  9.40712679e-01,
        -6.20620766e-01],
       [-1.08861812e-01, -1.94335581e-01, -4.72719939e-03,
        -1.55580274e+00],
       [ 3.26585437e-01,  1.09505933e+00, -1.93815175e-01,
         2.83388477e-03],
       [ 7.62032687e-01, -9.11578427e-01,  1.03525667e+00,
        -6.20620766e-01],
       [ 3.26585437e-01, -2.34967773e-01, -3.82903151e-01,
        -9.32348091e-01],
       [ 7.62032687e-01, -5.22017283e-01, -4.77447139e-01,
         1.24974319e+00],
       [-2.72154531e+00, -5.92192465e-01,  3.73448752e-01,
         9.38015860e-01],
       [-5.44309062e-01, -9.03959891e-01,  6.57080716e-01,
         2.83388477e-03],
       [ 7.62032687e-01, -9.67336685e-02, -7.61079102e-01,
         3.14561210e-01],
       [-5.44309062e-01, -7.88327444e-01,  4.67992740e-01,
        -1.24407542e+00],
       [ 3.26585437e-01,  3.20000255e-01, -4.72719939e-03,
        -3.08893440e-01],
       [-1.08861812e-01,  8.35097945e-01, -1.93815175e-01,
         2.83388477e-03],
       [-1.08861812e-01, -7.53536129e-01, -4.72719939e-03,
        -6.20620766e-01],
       [-5.44309062e-01, -2.94984907e-01,  3.11522440e+00,
        -3.08893440e-01],
       [-1.08861812e-01, -1.74019484e-01,  6.57080716e-01,
        -6.20620766e-01],
       [-5.44309062e-01,  1.60772851e-01,  1.79160857e+00,
        -6.20620766e-01],
       [-4.46333431e+00,  2.46946959e-01,  5.62536728e-01,
         3.14561210e-01],
       [ 3.26585437e-01, -7.12988587e-01, -1.23379904e+00,
         2.83388477e-03],
       [-5.44309062e-01, -7.16459253e-01,  4.67992740e-01,
         1.24974319e+00],
       [-1.08861812e-01, -9.05737550e-01, -1.93815175e-01,
        -1.55580274e+00],
       [ 1.19747994e+00, -7.54975186e-01,  1.60252059e+00,
         9.38015860e-01],
       [ 3.26585437e-01, -2.34713822e-01,  3.73448752e-01,
         2.83388477e-03],
       [-2.28609806e+00,  5.70385040e+00,  4.67992740e-01,
         3.14561210e-01],
       [-1.41520356e+00,  8.43335390e-02, -6.66535115e-01,
         1.24974319e+00],
       [ 3.26585437e-01,  6.49290315e-01,  1.60252059e+00,
         2.83388477e-03],
       [ 1.19747994e+00,  6.33291389e-01, -7.61079102e-01,
         3.14561210e-01],
       [-1.08861812e-01, -1.13748399e-01, -4.77447139e-01,
         1.24974319e+00],
       [ 7.62032687e-01,  1.19943327e+00, -1.23379904e+00,
         3.14561210e-01],
       [-1.41520356e+00, -4.15781029e-01, -3.82903151e-01,
         2.83388477e-03],
       [-1.08861812e-01, -8.41657196e-01, -1.23379904e+00,
        -1.24407542e+00],
       [ 7.62032687e-01, -2.11350311e-01, -3.82903151e-01,
        -9.32348091e-01],
       [ 3.26585437e-01,  1.69785483e+00, -4.77447139e-01,
        -6.20620766e-01],
       [-5.44309062e-01, -8.66290463e-01, -3.82903151e-01,
         9.38015860e-01],
       [ 7.62032687e-01, -2.66034470e-01, -3.82903151e-01,
        -3.08893440e-01],
       [-5.44309062e-01, -4.55905319e-01,  8.69331969e+00,
        -3.08893440e-01],
       [-1.08861812e-01, -1.62845632e-01, -6.66535115e-01,
         1.56147051e+00],
       [ 7.62032687e-01,  9.55978717e-01, -9.92711873e-02,
         3.14561210e-01],
       [-1.08861812e-01, -1.13748399e-01, -4.77447139e-01,
         6.26288535e-01],
       [-2.72154531e+00,  3.82672776e+00, -2.88359163e-01,
        -3.08893440e-01],
       [ 7.62032687e-01, -4.30256248e-01,  8.98167885e-02,
        -3.08893440e-01],
       [-1.08861812e-01, -2.31920359e-01,  1.03525667e+00,
        -9.32348091e-01],
       [-5.44309062e-01,  8.95284380e-01, -1.93815175e-01,
         3.14561210e-01],
       [-5.44309062e-01, -7.10364425e-01, -8.55623090e-01,
         3.14561210e-01],
       [-1.08861812e-01, -9.82346163e-01, -1.04471107e+00,
        -1.24407542e+00],
       [-1.08861812e-01, -1.07484269e-01,  7.51624704e-01,
        -6.20620766e-01],
       [-1.08861812e-01,  1.22110377e+00,  1.84360776e-01,
         1.24974319e+00],
       [ 7.62032687e-01, -1.97044394e-01, -5.71991127e-01,
         1.56147051e+00],
       [-1.41520356e+00, -9.52972473e-01,  2.16978452e+00,
         6.26288535e-01],
       [ 7.62032687e-01, -3.37225457e-01, -4.77447139e-01,
         2.83388477e-03],
       [ 1.19747994e+00, -2.27095286e-01, -6.66535115e-01,
         1.56147051e+00],
       [ 7.62032687e-01, -3.72440024e-01, -9.92711873e-02,
         1.56147051e+00],
       [ 3.26585437e-01, -8.90754429e-01,  8.98167885e-02,
        -1.55580274e+00],
       [-1.08861812e-01,  8.86396087e-01, -9.92711873e-02,
         9.38015860e-01],
       [-1.08861812e-01,  9.38202133e-01, -6.66535115e-01,
        -3.08893440e-01],
       [-1.08861812e-01,  1.22110377e+00,  1.84360776e-01,
         1.56147051e+00],
       [-1.08861812e-01, -3.85730137e-01,  2.78904764e-01,
         6.26288535e-01],
       [ 3.26585437e-01, -6.21312203e-01,  2.78904764e-01,
         6.26288535e-01],
       [-9.79756312e-01, -6.61775094e-01, -4.72719939e-03,
        -6.20620766e-01],
       [-1.08861812e-01, -7.92956859e-02,  9.40712679e-01,
         3.14561210e-01],
       [-1.08861812e-01, -3.85730137e-01,  2.78904764e-01,
         3.14561210e-01],
       [-5.44309062e-01,  1.30721959e-01,  8.98167885e-02,
         1.56147051e+00],
       [ 1.19747994e+00,  6.35830901e-01, -4.77447139e-01,
         2.83388477e-03],
       [ 3.26585437e-01, -5.56808597e-01, -3.82903151e-01,
         9.38015860e-01],
       [-5.44309062e-01, -9.81415008e-01, -4.77447139e-01,
        -1.24407542e+00],
       [ 7.62032687e-01,  3.87551275e-01, -8.55623090e-01,
         1.56147051e+00],
       [ 7.62032687e-01, -5.57739752e-01, -5.71991127e-01,
         1.56147051e+00],
       [-1.08861812e-01,  1.27257122e+00,  1.84360776e-01,
         2.83388477e-03],
       [ 7.62032687e-01,  1.14187100e+00, -4.77447139e-01,
         3.14561210e-01],
       [-1.08861812e-01, -7.89004647e-01, -9.92711873e-02,
         1.56147051e+00],
       [-5.44309062e-01, -8.02379410e-01, -7.61079102e-01,
         2.83388477e-03],
       [-5.44309062e-01, -8.15923474e-01, -4.77447139e-01,
         3.14561210e-01],
       [-5.44309062e-01, -7.28648911e-01,  8.98167885e-02,
        -6.20620766e-01],
       [-1.85065081e+00, -8.81696836e-01, -4.72719939e-03,
        -9.32348091e-01],
       [-1.08861812e-01, -7.92956859e-02,  9.40712679e-01,
         6.26288535e-01],
       [-1.08861812e-01, -1.38720267e-01,  6.57080716e-01,
        -1.55580274e+00],
       [-1.08861812e-01, -4.29579045e-01, -8.55623090e-01,
         9.38015860e-01],
       [-5.44309062e-01,  1.24235102e+00, -4.77447139e-01,
        -9.32348091e-01],
       [-1.08861812e-01, -9.63104164e-02, -6.66535115e-01,
         2.83388477e-03],
       [-1.85065081e+00, -9.11070525e-01, -1.93815175e-01,
        -1.24407542e+00],
       [ 3.26585437e-01, -4.81469740e-01, -5.71991127e-01,
        -6.20620766e-01],
       [ 7.62032687e-01, -8.44281359e-01, -9.92711873e-02,
        -6.20620766e-01],
       [-1.41520356e+00, -5.75008433e-01,  2.78904764e-01,
         1.56147051e+00]])

In [ ]:
X_train

array([[ 0.76203269,  0.92965244, -0.66653511,  1.24974319],
       [ 0.76203269,  0.16703698, -0.85562309,  0.93801586],
       [ 0.76203269, -0.27322975, -0.7610791 ,  1.56147051],
       ...,
       [-0.97975631,  0.29299678,  0.08981679,  0.62628854],
       [ 0.76203269,  0.80927957, -0.38290315,  0.93801586],
       [ 0.32658544, -0.23496777, -0.38290315, -0.62062077]])